version: '3.8'

services:
  postgres:
    build: .
    ports:
      - 9000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=testest_db
    restart: always