-- Base app schema

-- User
CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,

    pwd VARCHAR(255),
    pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
    pwd_token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);

-- Task
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,

    pwd VARCHAR(255),
    pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
    pwd_token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);