version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - 7777:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=info_db
    restart: always

# volumes can be used to have docker update when there are changes
# something with docker dev containers hmmm